### PR TITLE
.FIX metadata update on updateBytes.

### PR DESCRIPTION
**Pull request by cubiak**
Proposal -> Metadata recalculate on individual Line updates

### CODE REVIEW

**Comment by Luncher91** [comment]
You are right - I forgot about that. Thank you fro bringing that up! 👍 

Before merging I would like to have another test which checks if the metadata has been updated.

**Comment by Luncher91** [comment]
I spotted that we only need to update the checksum in this method but we need to update the checksum and the length when extending the line.

**Review by Luncher91 — APPROVED** [review]
Looks good to me so far. What do you think?

**Comment by cubiak** [comment]
it's all good now

**Pull request merged**
